# Generated by Django 5.1.7 on 2025-03-14 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_uuid', models.UUIDField(editable=False, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'FAQ'), (2, 'Conversation'), (3, 'Document')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_category', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Needs Review'), (2, 'Pre-Approved'), (3, 'Approved'), (4, 'Reject')], default=1)),
                ('is_edited', models.BooleanField(default=False)),
                ('in_brain', models.BooleanField(default=False)),
                ('language', models.IntegerField(choices=[(1, 'English'), (2, 'Malaysian'), (3, 'Chinese')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_content', to='api.knowledge')),
            ],
        ),
        migrations.CreateModel(
            name='Brain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('knowledge_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_content', to='api.knowledgecontent')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='knowledge',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_subcategory', to='api.subcategory'),
        ),
        migrations.AddConstraint(
            model_name='knowledgecontent',
            constraint=models.UniqueConstraint(fields=('knowledge', 'language'), name='unique_knowledge_language'),
        ),
    ]
