# Generated by Django 5.1.7 on 2025-03-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_category', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_uuid', models.UUIDField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('FAQ', 'FAQ'), ('Conversation', 'Conversation'), ('Document', 'Document')], default='FAQ', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_category', to='api.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_subcategory', to='api.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('needs_review', 'Needs Review'), ('pre_approved', 'Pre-Approved'), ('approved', 'Approved'), ('reject', 'Reject')], default='needs_review', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('in_brain', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ms', 'Malaysian'), ('cn', 'Chinese')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_content', to='api.knowledge')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('knowledge', 'language'), name='unique_knowledge_language')],
            },
        ),
    ]
