"""
Django settings for chatbot_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import logging
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from rich.logging import RichHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
app_env = os.getenv("DJANGO_ENV", "local").upper()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") 


# TODO: Temporary for development
FIXED_API_TOKEN = "4d4a50524f4432303232"

# MongoDB settings
MONGODB_USERNAME = os.getenv(f"{app_env}_MONGODB_USERNAME")
MONGODB_PASSWORD = os.getenv(f"{app_env}_MONGODB_PASSWORD")
MONGODB_CLUSTER = os.getenv(f"{app_env}_MONGODB_CLUSTER")
MONGODB_DATABASE = os.getenv(f"{app_env}_MONGODB_DATABASE", "chatbotdb")

# Postgresql settings
POSTGRE_DATABASE_NAME = os.getenv(f"{app_env}_POSTGRE_DATABASE_NAME")
POSTGRE_DATABASE_USER = os.getenv(f"{app_env}_POSTGRE_DATABASE_USER")
POSTGRE_DATABASE_PASSWORD = os.getenv(f"{app_env}_POSTGRE_DATABASE_PASSWORD")
POSTGRE_DATABASE_HOST = os.getenv(f"{app_env}_POSTGRE_DATABASE_HOST")
POSTGRE_DATABASE_PORT = os.getenv(f"{app_env}_POSTGRE_DATABASE_PORT")


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRE_DATABASE_NAME,
        'USER': POSTGRE_DATABASE_USER,
        'PASSWORD': POSTGRE_DATABASE_PASSWORD,
        'HOST': POSTGRE_DATABASE_HOST, 
        'PORT': POSTGRE_DATABASE_PORT,
    }
}

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    'django_celery_results',
    "django_celery_beat",
    "api",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "api.middleware.FixedTokenAuthMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chatbot_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "django.template.loaders.cached.Loader",
                    [
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
            ],
        },
    },
]


WSGI_APPLICATION = "chatbot_project.wsgi.application"

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = []
CORS_ALLOW_HEADERS = list(default_headers) + [""]

# Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "OPTIONS": {
            "MAX_ENTRIES": 1000,  # Limit cache entries
            "CULL_FREQUENCY": 3,  # Remove 1/3 of entries when max is reached
        },
    }
}

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Session Settings
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = False

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]


LOG_DIR = "logs/"
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# added logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # TODO: to be confirmed
         "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": "django.log",
            "maxBytes": 5242880,  # 5MB
            "backupCount": 3,
            "formatter": "verbose",
        },

        # comfirmed handelers
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        'rich_console': {
            'level': 'INFO',  # Set the level to DEBUG for rich logs
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        "api_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "api.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 30,  # Keep one month's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "celery_tasks": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "celery_tasks.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 30,  # Keep one month's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "celery_worker": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "celery_worker.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 30,  # Keep one month's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "celery_beat": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "celery_beat.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 30,  # Keep one month's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "celery_tasks": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "celery_tasks.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 30,  # Keep one month's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
        "rabbitmq_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "rabbitmq.log"),
            "when": "midnight",  # Rotate at midnight
            "interval": 1,
            "backupCount": 7,  # Keep seven-day's worth of log files
            "formatter": "verbose",
            "encoding": "utf8",
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
    "loggers": {
        # TODO: loggers to be confirm
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.server": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Comfirmed loggers
        "api": {
            "handlers": ["console", "api_file"],
            "level": "INFO",
            "propagate": False,
        },
        'brain_manager': {
            'handlers': ['rich_console', 'file'],  # Use the rich_console handler for logging
            'level': 'INFO',  # Change to INFO or ERROR depending on verbosity
            'propagate': False,
        },
        "celery.worker": {
            "handlers": ["console","celery_worker"],
            "level": "INFO",
            "propagate": True,
        },
        "celery.beat": {
            "handlers": ["console","celery_beat"],
            "level": "INFO",
            "propagate": True,
        },
        "celery.tasks": {
            "handlers": ["console","celery_tasks"],
            "level": "INFO",
            "propagate": True,
        },
        "rabbitmq": {
            "handlers": ["console", "rabbitmq_file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# Media Files
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MAX_UPLOAD_SIZE = 5242880  # 5MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



#  Celery settings
CELERY_BROKER_URL = os.getenv(f"{app_env}_CELERY_BROKER_URL")
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_BACKEND = "django-db"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_STORE_REALTIME_DATA_EVERY_INTERVAL = 1