name: Deploy to AWS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH into AWS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "13.236.193.147"
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            cd ~/chatbot/django_chabot_backend
             git checkout staging
             git pull origin staging
             pm2 restart chatbot_server
